### PR TITLE
Update main.css

### PR DESCRIPTION
**Pull request by lorenamd**

### CODE REVIEW

**Comment by lorenamd** [comment]
And I could suggest to change the avatar picture and the gradient color on the left for the pictures below (if you change the gradient, then you would need to change the color on the line 2482 for #535454)

bg
avatar

**Comment by pin3da** [comment]
Hello @lorenamd !

I totally agree with the change of the gradient and the avatar. Could you include those changes in this PR, I will be very happy to merge it (:

Thank you !

**Comment by lorenamd** [comment]
I am new in Github, but I have tried before to upload these images in their folder but it says "File uploads require push access to this repository".

**Comment by pin3da** [comment]
I will add the images in another PR. Thank you for your help 😸

**Pull request merged**
